#!/bin/bash

#Сохранение имени программы и каталога
FROM=$1
NAME=$2
#Проверка кол-ва аргументов
if [ $# -lt 3 ]
then
	echo -e "\033[0;31mError: insufficient number of arguments\033[0m"
	exit 1
fi

#Проверка существования каталока FROM
if [ ! -e $FROM ]
then
        echo -e "\033[0;31mError: the directory $FROM does not exist\033[0m"
	exit 2
fi


#Проверка прав на исполнение каталока FROM
if [ ! -x $FROM ]
then
        echo -e "\033[0;31mError: the directory $FROM need the execution permisson\033[0m"
        exit 3
fi

#Проверка существования программы NAME
if [ ! -r $FROM/$NAME -o ! -x $FROM/$NAME ]
then
	echo -e "\033[0;31mError: the program $NAME does not exist\033[0m"
	exit 4 
fi

#Проверка прав на исполнение программы NAME 
if [ ! -x $NAME ]
then
        echo -e "\033[0;31mError: the program $NAME need the execution permisson\033[0m"
        exit 5
fi

#Копирование программы в случае ее отсутствия
if [ ! -e $NAME ]
then
	cp $FROM/$NAME .
fi

#Выполнение программы для всех файлов
shift
shift
while [ $# -gt 0 ]
do
	if [ ! -f $1 ]; then
		echo -e "\033[0;31mError: the file $1 does not exist\033[0m"
		exit 6
	fi		
	./$NAME $1
	shift
done
exit 0
