#!/bin/bash

#Тест-драйвер для lab1

#Создание временных файлов
cd /home/evgeny/BashLabs/Lab1-sem5
int=1
while [ $int -le 25 ]
do
	touch arg$int
	let "int+=1"
done

#Проверка кол-ва аргументов
./lab1 /home/evgeny/Bash/temp 
./lab1 /home mytouch
./lab1 sdfsd sadfkl13fesd
echo

#Проверка существования каталока FROM
./lab1 /pkljel/sdfs mytouch arg1 arg2 arg3 arg4
./lab1 /home/evgeny/Bash/mytest/ name arg1 arg2 arg3
./lab1 askfj1d/ mytouch arg1
echo

#Проверка прав на исполнение каталога FROM
chmod 444 temp
./lab1 /home/evgeny/BashLabs/Lab1-sem5/temp mytouch arg1 arg2 arg3
chmod 666 temp
./lab1 /home/evgeny/BashLabs/Lab1-sem5/temp mytouch arg1 arg2 arg3
chmod 775 temp
echo

#Проверка существования программы NAME
./lab1 /home/evgeny/BashLabs/Lab1-sem5/temp notexist arg1 arg2 arg3
./lab1 /home/evgeny/BashLabs/Lab1-sem5/temp notexisttoo arg1 arg2 arg3
echo

#Проверка прав на исполнение программы NAME
chmod 444 temp/mytouch 
./lab1 /home/evgeny/BashLabs/Lab1-sem5/temp mytouch arg1 arg2 arg3
chmod 666 temp/mytouch 
./lab1 /home/evgeny/BashLabs/Lab1-sem5/temp mytouch arg1 arg2 arg3
chmod 777 temp/mytouch
echo

#Проверка существования файлов FILES
rm arg2
./lab1 /home/evgeny/BashLabs/Lab1-sem5/temp mytouch arg1 arg2 arg3
touch arg2
rm arg1 arg2
./lab1 /home/evgeny/BashLabs/Lab1-sem5/temp mytouch arg1 arg2 arg3
touch arg1 arg2
rm arg3
./lab1 /home/evgeny/BashLabs/Lab1-sem5/temp mytouch arg1 arg2 arg3
touch arg3
echo

#Копирование программы в случае ее отсутствия
./lab1 /home/evgeny/BashLabs/Lab1-sem5/temp mytouch arg1
if [ -e mytouch ] 
then
	echo "mytouch скопирована в текущий каталог"
fi
./lab1 /home/evgeny/BashLabs/Lab1-sem5/temp mytouch arg1
if [ -e mytouch ] 
then
        echo "mytouch не скопирована в текущий каталог, так как уже присутствует в нем"
	rm mytouch
fi
echo

#Выполнение программы для всех файлов
./lab1 /home/evgeny/BashLabs/Lab1-sem5/temp mytouch arg1
if [ $? -eq 0 ]
then
	echo "Succes1"
fi
./lab1 /home/evgeny/BashLabs/Lab1-sem5/temp mytouch arg1 arg2 arg3 arg4 arg5
if [ $? -eq 0 ]
then
        echo "Succes2"
fi
./lab1 /home/evgeny/BashLabs/Lab1-sem5/temp mytouch arg1 arg2 arg3 arg4 arg5 arg6 arg7 arg8 arg9 arg10 arg11 arg12 arg13 arg14 arg15 arg16 arg17 arg18 arg19 arg20 arg21 arg22 arg23 arg24 arg25
if [ $? -eq 0 ]
then
        echo "Succes3"
	echo
fi

#Удаление временных файлов
rm mytouch arg*
